version: '3'
services:
  koerbyapi:
    image: "ubl:koerbyapi"
    ports: 
      - "6662:6662"
  daftapi:
    image: "ubl:daftapi"
    ports:
      - "6661:6661"
#    environment:
#      - "HTTP_PROXY=http://proxy.uni-leipzig.de:3128"
#      - "HTTPS_PROXY=http://proxy.uni-leipzig.de:3128"
  unifiedapi:
    image: "nginx"
    ports: 
      - "6660:6660"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - daftapi
      - koerbyapi
